version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  json:
    format: '{"timestamp": "%(asctime)s", "logger": "%(name)s", "level": "%(levelname)s", "module": "%(module)s", "function": "%(funcName)s", "line": %(lineno)d, "message": "%(message)s"}'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/rag_chatbot.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: logs/rag_chatbot_errors.log
    maxBytes: 10485760  # 10MB
    backupCount: 5
  
  json_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: json
    filename: logs/rag_chatbot.jsonl
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  # RAG Pipeline Components
  rag_pipeline:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  llm_integration:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  vector_stores:
    level: DEBUG
    handlers: [console, file]
    propagate: false
  
  governance:
    level: INFO
    handlers: [console, file, json_file]
    propagate: false
  
  web_interface:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  # Third-party libraries
  transformers:
    level: WARNING
    handlers: [file]
    propagate: false
  
  sentence_transformers:
    level: WARNING
    handlers: [file]
    propagate: false
  
  chromadb:
    level: WARNING
    handlers: [file]
    propagate: false
  
  fastapi:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  streamlit:
    level: INFO
    handlers: [console, file]
    propagate: false
  
  uvicorn:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]
